In [24]:
'''
Merge Two Dictionaries:
 Combine dict1 = {"a": 1, "b": 2} and dict2 = {"b": 3, "c": 4}. 
 If a key exists in both, sum their values.
'''

f1={"a": 1, "b": 2} 
f2={"b": 3, "c": 4}
res=f1.copy()
for keys,values in f2.items():
    if keys in res:
        res[keys]+=values
    else:
        res[keys]=values

print(res)

from collections import Counter
merg=dict(Counter(f1)+Counter(f2))
print(merg)

{'a': 1, 'b': 5, 'c': 4}
{'a': 1, 'b': 5, 'c': 4}

In [29]:
'''
Given a list of integers, return all elements that appear more than once.
'''
arr=[1,1,2,3,4,4,5,6,5]
# arr=[1,1]
d=dict()
res=[]
for i in arr:
    if i in d:
        d[i]+=1
    else:
        d[i]=0
print(d)
for key,value in d.items():
    if value>=1:
        res.append(key)
print(res)

{1: 1, 2: 0, 3: 0, 4: 1, 5: 1, 6: 0}
[1, 4, 5]

In [38]:
''' 
Second Largest Number:
 Find the second largest number in a list without using the built-in sort()
'''

arr=[7,12,5,6,3,11]
sec=first=-1
for i in arr:
    if first<i :
        sec=first
        first=i
    if sec<i and first>i:
        sec=i

print(sec,first)

11 12

In [46]:
'''
 Write a program to reverse a string word by word
   (e.g., "Data Engineering is fun" becomes "fun is Engineering Data"
'''

st= "Data Engineering is fun"

print(st[::-1])
ls=st[::-1].split(" ")
m=[re[::-1] for re in ls]
print(m)
res=" ".join(m)
print(res)

nuf si gnireenignE ataD
['fun', 'is', 'Engineering', 'Data']
fun is Engineering Data

In [50]:
'''
pandas
'''

import pandas as pd

# Raw Data
sales_data = [
    {'Product': 'Laptop', 'Category': 'Electronics', 'Revenue': 1200},
    {'Product': 'Mouse', 'Category': 'Electronics', 'Revenue': 50},
    {'Product': 'Desk', 'Category': 'Furniture', 'Revenue': 300},
    {'Product': 'Laptop', 'Category': 'Electronics', 'Revenue': 1100},
    {'Product': 'Chair', 'Category': 'Furniture', 'Revenue': 150},
    {'Product': 'Mouse', 'Category': 'Electronics', 'Revenue': 45}
]

df=pd.DataFrame(sales_data)
df.head()

  Product     Category  Revenue
0  Laptop  Electronics     1200
1   Mouse  Electronics       50
2    Desk    Furniture      300
3  Laptop  Electronics     1100
4   Chair    Furniture      150

In [52]:
df.head()
'''
Find the Total Revenue for each Category.
'''
tot_rev=df.groupby('Category')['Revenue'].sum()
print(tot_rev)

Category
Electronics    2395
Furniture       450
Name: Revenue, dtype: int64

In [51]:
'''
Find the Average Revenue per Product.
'''
avg_rev_per_prod=df.groupby('Product')['Revenue'].mean()
avg_rev_per_prod

Product
Chair      150.0
Desk       300.0
Laptop    1150.0
Mouse       47.5
Name: Revenue, dtype: float64

In [54]:
# Table 1: Sales
df_sales = pd.DataFrame({
    'Product': ['Laptop', 'Mouse', 'Desk'],
    'Revenue': [1200, 50, 300]
})

# Table 2: Suppliers
df_suppliers = pd.DataFrame({
    'Product': ['Laptop', 'Mouse', 'Monitor'],
    'Supplier': ['Dell', 'Logitech', 'Samsung']
})

res=pd.concat([df_sales,df_suppliers],axis=0)
print(res)
left_join_data=pd.merge(df_sales,df_suppliers,on='Product' , how='left')
print(left_join_data)

   Product  Revenue  Supplier
0   Laptop   1200.0       NaN
1    Mouse     50.0       NaN
2     Desk    300.0       NaN
0   Laptop      NaN      Dell
1    Mouse      NaN  Logitech
2  Monitor      NaN   Samsung
  Product  Revenue  Supplier
0  Laptop     1200      Dell
1   Mouse       50  Logitech
2    Desk      300       NaN

In [ ]:
res=left_join_data.fillna('unknown')
res['Profit']=0
res['Profit']=res['Profit'].fillna(0).astype(float)
res['Profit']=0.15*res['Revenue']

  Product  Revenue  Supplier
0  Laptop     1200      Dell
1   Mouse       50  Logitech
2    Desk      300   unknown

  Product  Revenue  Supplier  Profit
0  Laptop     1200      Dell     0.0
1   Mouse       50  Logitech     0.0
2    Desk      300   unknown     0.0

In [ ]:

res

  Product  Revenue  Supplier  Profit
0  Laptop     1200      Dell   180.0
1   Mouse       50  Logitech     7.5
2    Desk      300   unknown    45.0

In [ ]:
res_df=res[res['Profit']>50]
res_df

  Product  Revenue Supplier  Profit
0  Laptop     1200     Dell   180.0

In [68]:
class BankAccount:
    def __init__(self, balance):
        # PRIVATE variable (Hidden from the outside)
        self.__balance = balance 

    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount
            print(f"Deposited {amount}. New balance is {self.__balance}")

    def get_balance(self):
        # Public way to "peek" at the private data
        return self.__balance

# Create an account
my_acc = BankAccount(1000)

# 1. This will FAIL (AttributeError)
# print(my_acc.__balance) 

# 2. You MUST use the methods provided
my_acc.deposit(500)
print(f"Current Balance: {my_acc.get_balance()}")

Deposited 500. New balance is 1500
Current Balance: 1500

In [17]:
li=list()
se=set()
tu=tuple()
tu

()

In [14]:
#tuples are immutable, ordered and allows duplicates
m=(3,1,2,3)
tu=tuple(m)
tu
# type(tu)
# tu[0]='11'

(3, 1, 2, 3)

In [ ]:
#list objects are mutable,ordered and allows duplicates

li.append(1)
li.append(2)
li.append(3)
li.append("1")
li

[1, 2, 3, '1']

In [ ]:
#set objects are mutable,unordered and dosen't allow duplicates

se.add(1)
se.add(2)
se.add(3)
se.add(1)
se.add(0)
se

{0, 1, 2, 3}

In [22]:
# Table 1: Sales
import pandas as pd
df_sales = pd.DataFrame({
    'Product': ['Laptop', 'Mouse', 'Desk'],
    'Revenue': [1200, 50, 300]
})

# Table 2: Suppliers
df_suppliers = pd.DataFrame({
    'Product': ['Laptop', 'Mouse', 'Monitor'],
    'Supplier': ['Dell', 'Logitech', 'Samsung']
})

df_sales

  Product  Revenue
0  Laptop     1200
1   Mouse       50
2    Desk      300

In [23]:
df_suppliers

   Product  Supplier
0   Laptop      Dell
1    Mouse  Logitech
2  Monitor   Samsung

In [36]:
res=pd.concat(
    [
    df_sales.loc[:,['Product','Revenue']],
    df_suppliers.loc[:,['Product','Supplier']]
    ],
    keys=['df_sales','df_suppliers'],axis=1
)
res

  df_sales         df_suppliers
   Product Revenue      Product  Supplier
0   Laptop    1200       Laptop      Dell
1    Mouse      50        Mouse  Logitech
2     Desk     300      Monitor   Samsung

In [1]:
a=[["a", "b", "c"], ["x", "b", "c"], ["x", "y", "c"], ["x", "y", "z"]]
a

[['a', 'b', 'c'], ['x', 'b', 'c'], ['x', 'y', 'c'], ['x', 'y', 'z']]

In [ ]:
for a,b in zip(a,a[1:]):
    print(a,b)
    print(diff(a,b))
    print('----')

['a', 'b', 'c'] ['x', 'b', 'c']
----
['x', 'b', 'c'] ['x', 'y', 'c']
----
['x', 'y', 'c'] ['x', 'y', 'z']
----

In [5]:
my_dict1 = {'a' : 1, 'b' : 2, 'c' : 3}
my_dict2 = {'d' : 4, 'e' : 5, 'f' : 6}
result = { **my_dict1, **my_dict2}

print(result)
my_dict3 = {'d' : 14, 'e' : 15, 'f' : 16}
res1={**my_dict3,**my_dict2}
print(res1)

result = {key: value for d in (my_dict1, my_dict2) for key, value in d.items()}
print(result)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}
{'d': 4, 'e': 5, 'f': 6}
{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}

In [6]:
person = [
  {
    'name' : 'alice',
    'age' : 22,
    'id' : 92345
  },
  {
    'name' : 'bob',
    'age' : 24,
    'id' : 52353
  },
  {
    'name' : 'tom',
    'age' : 23,
    'id' : 62257
  }
]

res=lambda x:x['age']
m=sorted(person,key=res)

print(m)

[{'name': 'alice', 'age': 22, 'id': 92345}, {'name': 'tom', 'age': 23, 'id': 62257}, {'name': 'bob', 'age': 24, 'id': 52353}]

In [10]:
b=[1,[2,[3,4],5],6]
res=[]
def uglylist(b,res):
    for item in b:
        if isinstance(item,list):
            uglylist(item,res)
        else:
            res.append(item)
    return res
print(uglylist(b,res))

[1, 2, 3, 4, 5, 6]

In [11]:
mtx=[["a", "b", "c"], ["x", "b", "c"], ["x", "y", "c"], ["x", "y", "z"]]
res1=[]
res2=[]
for row in mtx:
    for val in row:
        res1.append(val)
print(res1)

['a', 'b', 'c', 'x', 'b', 'c', 'x', 'y', 'c', 'x', 'y', 'z']

In [14]:
res2=[  val for row in mtx for val in row ]
print(res2)

['a', 'b', 'c', 'x', 'b', 'c', 'x', 'y', 'c', 'x', 'y', 'z']

In [20]:
def change(x):
    x =x+ ["getoutofcomfortzone"]

a = [1, 2, 3]
change(a)
print(a)

[1, 2, 3]

In [ ]:
a = [[1, 2]] * 3
a[0].append(99)

print(a)

[[1, 2, 99], [1, 2, 99], [1, 2, 99]]

In [ ]:
def is_leap_year(year):
    return (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)

print(is_leap_year(1800))  # False
print(is_leap_year(2023))  # False

False
False

In [35]:
def longest_word(sentence):
    words = sentence.split()
    d=dict()
    for word in words:
        d[word]=len(word)
    print(d)
    m=lambda wor: d[wor]
    print(sorted(d,key=m))
print(longest_word("The fox jumps over the lazy dog"))  #

{'The': 3, 'fox': 3, 'jumps': 5, 'over': 4, 'the': 3, 'lazy': 4, 'dog': 3}
['The', 'fox', 'the', 'dog', 'over', 'lazy', 'jumps']
None

In [36]:
from abc import ABC, abstractmethod

class Greet(ABC):
    @abstractmethod
    def say_hello(self):
        pass  # Abstract method

class English(Greet):
    def say_hello(self):
        return "Hello!"

g = English()
print(g.say_hello())

Hello!

In [1]:


def dec(func):
    print('entered dec function')
    def wrapper(name,id,dept):
        print('before main')
        func(name,id,dept)
        print('after main')
    return wrapper

@dec
def my_details(name,id,dept):
    print(name,'--',id,'--',dept)


my_details('bharat',123,'IT')

entered dec function
before main
bharat -- 123 -- IT
after main

In [2]:
''' 
multiple decorators
'''
def dec1(func):
    def wrap(name,id):
        print('before dec1')
        func(name,id)
        print('after dec1')
    return wrap

def dec2(func):
    def wrapper(name,id):
        print('before dec2')
        func(name,id)  #dec1(name,id)
        print('after dec2')
    return wrapper


# it works like dec1(dec2(greet))
@dec1
@dec2
def greet(name,id):
    print(name,id)

greet('bharadwaj',12)

before dec1
before dec2
bharadwaj 12
after dec2
after dec1

In [16]:
inp1='abcdaf'
inp2='acbcf'
rows=len(inp1)+1
cols=len(inp2)+1
arr=[[0]*cols for row in range(rows)]
print(arr)
for i in range(1,rows):
    for j in range(1,cols):
        if inp1[i-1]!=inp2[j-1]:
            arr[i][j]=max(arr[i-1][j],arr[i][j-1])
        else:
            arr[i][j]=1+arr[i-1][j-1]
print(arr)

[[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]]
[[0, 0, 0, 0, 0, 0], [0, 1, 1, 1, 1, 1], [0, 1, 1, 2, 2, 2], [0, 1, 2, 2, 3, 3], [0, 1, 2, 2, 3, 3], [0, 1, 2, 2, 3, 3], [0, 1, 2, 2, 3, 4]]