In [24]:
'''
Merge Two Dictionaries:
 Combine dict1 = {"a": 1, "b": 2} and dict2 = {"b": 3, "c": 4}. 
 If a key exists in both, sum their values.
'''

f1={"a": 1, "b": 2} 
f2={"b": 3, "c": 4}
res=f1.copy()
for keys,values in f2.items():
    if keys in res:
        res[keys]+=values
    else:
        res[keys]=values

print(res)

from collections import Counter
merg=dict(Counter(f1)+Counter(f2))
print(merg)

{'a': 1, 'b': 5, 'c': 4}
{'a': 1, 'b': 5, 'c': 4}

In [29]:
'''
Given a list of integers, return all elements that appear more than once.
'''
arr=[1,1,2,3,4,4,5,6,5]
# arr=[1,1]
d=dict()
res=[]
for i in arr:
    if i in d:
        d[i]+=1
    else:
        d[i]=0
print(d)
for key,value in d.items():
    if value>=1:
        res.append(key)
print(res)

{1: 1, 2: 0, 3: 0, 4: 1, 5: 1, 6: 0}
[1, 4, 5]

In [38]:
''' 
Second Largest Number:
 Find the second largest number in a list without using the built-in sort()
'''

arr=[7,12,5,6,3,11]
sec=first=-1
for i in arr:
    if first<i :
        sec=first
        first=i
    if sec<i and first>i:
        sec=i

print(sec,first)

11 12

In [46]:
'''
 Write a program to reverse a string word by word
   (e.g., "Data Engineering is fun" becomes "fun is Engineering Data"
'''

st= "Data Engineering is fun"

print(st[::-1])
ls=st[::-1].split(" ")
m=[re[::-1] for re in ls]
print(m)
res=" ".join(m)
print(res)

nuf si gnireenignE ataD
['fun', 'is', 'Engineering', 'Data']
fun is Engineering Data

In [50]:
'''
pandas
'''

import pandas as pd

# Raw Data
sales_data = [
    {'Product': 'Laptop', 'Category': 'Electronics', 'Revenue': 1200},
    {'Product': 'Mouse', 'Category': 'Electronics', 'Revenue': 50},
    {'Product': 'Desk', 'Category': 'Furniture', 'Revenue': 300},
    {'Product': 'Laptop', 'Category': 'Electronics', 'Revenue': 1100},
    {'Product': 'Chair', 'Category': 'Furniture', 'Revenue': 150},
    {'Product': 'Mouse', 'Category': 'Electronics', 'Revenue': 45}
]

df=pd.DataFrame(sales_data)
df.head()

  Product     Category  Revenue
0  Laptop  Electronics     1200
1   Mouse  Electronics       50
2    Desk    Furniture      300
3  Laptop  Electronics     1100
4   Chair    Furniture      150

In [52]:
df.head()
'''
Find the Total Revenue for each Category.
'''
tot_rev=df.groupby('Category')['Revenue'].sum()
print(tot_rev)

Category
Electronics    2395
Furniture       450
Name: Revenue, dtype: int64

In [51]:
'''
Find the Average Revenue per Product.
'''
avg_rev_per_prod=df.groupby('Product')['Revenue'].mean()
avg_rev_per_prod

Product
Chair      150.0
Desk       300.0
Laptop    1150.0
Mouse       47.5
Name: Revenue, dtype: float64

In [54]:
# Table 1: Sales
df_sales = pd.DataFrame({
    'Product': ['Laptop', 'Mouse', 'Desk'],
    'Revenue': [1200, 50, 300]
})

# Table 2: Suppliers
df_suppliers = pd.DataFrame({
    'Product': ['Laptop', 'Mouse', 'Monitor'],
    'Supplier': ['Dell', 'Logitech', 'Samsung']
})

res=pd.concat([df_sales,df_suppliers],axis=0)
print(res)
left_join_data=pd.merge(df_sales,df_suppliers,on='Product' , how='left')
print(left_join_data)

   Product  Revenue  Supplier
0   Laptop   1200.0       NaN
1    Mouse     50.0       NaN
2     Desk    300.0       NaN
0   Laptop      NaN      Dell
1    Mouse      NaN  Logitech
2  Monitor      NaN   Samsung
  Product  Revenue  Supplier
0  Laptop     1200      Dell
1   Mouse       50  Logitech
2    Desk      300       NaN

In [ ]:
res=left_join_data.fillna('unknown')
res['Profit']=0
res['Profit']=res['Profit'].fillna(0).astype(float)
res['Profit']=0.15*res['Revenue']

  Product  Revenue  Supplier
0  Laptop     1200      Dell
1   Mouse       50  Logitech
2    Desk      300   unknown

  Product  Revenue  Supplier  Profit
0  Laptop     1200      Dell     0.0
1   Mouse       50  Logitech     0.0
2    Desk      300   unknown     0.0

In [ ]:

res

  Product  Revenue  Supplier  Profit
0  Laptop     1200      Dell   180.0
1   Mouse       50  Logitech     7.5
2    Desk      300   unknown    45.0

In [ ]:
res_df=res[res['Profit']>50]
res_df

  Product  Revenue Supplier  Profit
0  Laptop     1200     Dell   180.0

In [68]:
class BankAccount:
    def __init__(self, balance):
        # PRIVATE variable (Hidden from the outside)
        self.__balance = balance 

    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount
            print(f"Deposited {amount}. New balance is {self.__balance}")

    def get_balance(self):
        # Public way to "peek" at the private data
        return self.__balance

# Create an account
my_acc = BankAccount(1000)

# 1. This will FAIL (AttributeError)
# print(my_acc.__balance) 

# 2. You MUST use the methods provided
my_acc.deposit(500)
print(f"Current Balance: {my_acc.get_balance()}")

Deposited 500. New balance is 1500
Current Balance: 1500